<!--
/**
 * Webkul Software.
 *
 * @category  Webkul 
 * @package   Webkul_GiftCard
 * @author    Webkul Software Private Limited
 * @copyright Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
-->
<?php $productType = $block->getproductType()?>
<script type="text/javascript">
require(
    [
        'jquery'
    ], function($){
    $(document).ready(function(){
        if ('<?php echo $productType; ?>' == 'giftcard') {
            $("span:contains('To')").each(function(index){
                var inputs = $(this).parent().next('div').find('input');
                inputs.attr('data-validate',"{required:true, 'validate-email':true}");
                inputs.attr('placeholder',"Enter recipient's email address");
                
                inputs.after('<p class="note">Make sure you\'ve got the right email!</p>');
            });
                        
            $("textarea.product-custom-option").attr('placeholder',"Hope you enjoy this Aulie's egift card!");
            
        }
    });
});
</script>